language: node_js
node_js:
  - "4"  # LTS   from 2015-10 maintenance till 2018-04
  - "6"  # LTS   from 2016-10 maintenance till 2019-04
  - "7"  # devel till 2017-08
#  - "8"  # LTS   from 2017-10 maintenance till 2020-04

# coveralls integration
after_success:
  - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=l5BVLErJWiimRGJLZpHPuhKyyUUkpEv6W node_modules/.bin/builder test --coveralls

# Fix the c++ compiler on Ubuntu 14.04
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
